robot:
  discrete_actions:
    - name: dont_move_waypoint
      angular: -5
    - name: set_waypoint_0
      angular: -2.00
    - name: set_waypoint_1
      angular: -1.95
    - name: set_waypoint_2
      angular: -1.90
    - name: set_waypoint_3
      angular: -1.85
    - name: set_waypoint_4
      angular: -1.80
    - name: set_waypoint_5
      angular: -1.75
    - name: set_waypoint_6
      angular: -1.70
    - name: set_waypoint_7
      angular: -1.65
    - name: set_waypoint_8
      angular: -1.60
    - name: set_waypoint_9
      angular: -1.55
    - name: set_waypoint_10
      angular: -1.50
    - name: set_waypoint_11
      angular: -1.45
    - name: set_waypoint_12
      angular: -1.40
    - name: set_waypoint_13
      angular: -1.35
    - name: set_waypoint_14
      angular: -1.30
    - name: set_waypoint_15
      angular: -1.25
    - name: set_waypoint_16
      angular: -1.20
    - name: set_waypoint_17
      angular: -1.15
    - name: set_waypoint_18
      angular: -1.10
    - name: set_waypoint_19
      angular: -1.05
    - name: set_waypoint_20
      angular: -1.00
    - name: set_waypoint_21
      angular: -0.95
    - name: set_waypoint_22
      angular: -0.90
    - name: set_waypoint_23
      angular: -0.85
    - name: set_waypoint_24
      angular: -0.80
    - name: set_waypoint_25
      angular: -0.75
    - name: set_waypoint_26
      angular: -0.70
    - name: set_waypoint_27
      angular: -0.65
    - name: set_waypoint_28
      angular: -0.60
    - name: set_waypoint_29
      angular: -0.55
    - name: set_waypoint_30
      angular: -0.50
    - name: set_waypoint_31
      angular: -0.45
    - name: set_waypoint_32
      angular: -0.40
    - name: set_waypoint_33
      angular: -0.35
    - name: set_waypoint_34
      angular: -0.30
    - name: set_waypoint_35
      angular: -0.25
    - name: set_waypoint_36
      angular: -0.20
    - name: set_waypoint_37
      angular: -0.15
    - name: set_waypoint_38
      angular: -0.10
    - name: set_waypoint_39
      angular: -0.05
    - name: set_waypoint_40
      angular: 0.00
    - name: set_waypoint_41
      angular: 0.05
    - name: set_waypoint_42
      angular: 0.10
    - name: set_waypoint_43
      angular: 0.15
    - name: set_waypoint_44
      angular: 0.20
    - name: set_waypoint_45
      angular: 0.25
    - name: set_waypoint_46
      angular: 0.30
    - name: set_waypoint_47
      angular: 0.35
    - name: set_waypoint_48
      angular: 0.40
    - name: set_waypoint_49
      angular: 0.45
    - name: set_waypoint_50
      angular: 0.50
    - name: set_waypoint_51
      angular: 0.55
    - name: set_waypoint_52
      angular: 0.60
    - name: set_waypoint_53
      angular: 0.65
    - name: set_waypoint_54
      angular: 0.70
    - name: set_waypoint_55
      angular: 0.75
    - name: set_waypoint_56
      angular: 0.80
    - name: set_waypoint_57
      angular: 0.85
    - name: set_waypoint_58
      angular: 0.90
    - name: set_waypoint_59
      angular: 0.95
    - name: set_waypoint_60
      angular: 1.00
    - name: set_waypoint_61
      angular: 1.05
    - name: set_waypoint_62
      angular: 1.10
    - name: set_waypoint_63
      angular: 1.15
    - name: set_waypoint_64
      angular: 1.20
    - name: set_waypoint_65
      angular: 1.25
    - name: set_waypoint_66
      angular: 1.30
    - name: set_waypoint_67
      angular: 1.35
    - name: set_waypoint_68
      angular: 1.40
    - name: set_waypoint_69
      angular: 1.45
    - name: set_waypoint_70
      angular: 1.50
    - name: set_waypoint_71
      angular: 1.55
    - name: set_waypoint_72
      angular: 1.60
    - name: set_waypoint_73
      angular: 1.65
    - name: set_waypoint_74
      angular: 1.70
    - name: set_waypoint_75
      angular: 1.75
    - name: set_waypoint_76
      angular: 1.80
    - name: set_waypoint_77
      angular: 1.85
    - name: set_waypoint_78
      angular: 1.90
    - name: set_waypoint_79
      angular: 1.95
    - name: set_waypoint_80
      angular: 2.00
  continuous_actions:
    angular_range: [-2, 2]