robot:
  discrete_actions:
    - name: dont_move_waypoint
      angular: -0.5
    - name: set_waypoint_on_goal
      angular: 0.5
    - name: set_waypoint_0
      angular: -2.00
    - name: set_waypoint_1
      angular: -1.80
    - name: set_waypoint_2
      angular: -1.60
    - name: set_waypoint_3
      angular: -1.40
    - name: set_waypoint_4
      angular: -1.20
    - name: set_waypoint_5
      angular: -1.00
    - name: set_waypoint_6
      angular: -0.80
    - name: set_waypoint_7
      angular: -0.60
    - name: set_waypoint_8
      angular: -0.40
    - name: set_waypoint_9
      angular: -0.20
    - name: set_waypoint_10
      angular: 0.00
    - name: set_waypoint_11
      angular: 0.20
    - name: set_waypoint_12
      angular: 0.40
    - name: set_waypoint_13
      angular: 0.60
    - name: set_waypoint_14
      angular: 0.80
    - name: set_waypoint_15
      angular: 1.00
    - name: set_waypoint_16
      angular: 1.20
    - name: set_waypoint_17
      angular: 1.40
    - name: set_waypoint_18
      angular: 1.60
    - name: set_waypoint_19
      angular: 1.80
    - name: set_waypoint_20
      angular: 2.00
  #continuous_actions:
  #  angular_range: [-2, 2]