waypoint_generator:
  continuous_actions:
    # actually x dont wanna change to much 
    x_range: [-1.2, 1.2]
    # actually y 
    y_range: [-1.2, 1.2]

  discrete_actions:
    - name: Outermost ring
      # arena_bringup/launch/sublaunch_training/single_env_training_waypoint.launch to change look ahead distance
      linear: 1.6
      # start stop num like the params in np.linspace
      angular: [-3.141592653589793, 3.141592653589793,20]
