waypoint_generator:
  discrete_actions:
    - name: Outermost ring
      # arena_bringup/launch/sublaunch_training/single_env_training_waypoint.launch to change look ahead distance
      linear: 1.2
      # start stop num like the params in np.linspace
      angular: [-3.141592653589793/180*90, 3.141592653589793/180*90, 5]
    - name: Center
      linear: 0
      angular: 0

  continuous_actions:
    # actually x dont wanna change to much 
    linear_range: [-2, 2]
    # actually y 
    angular_range: [-2,2]
